apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-webapp
  template:
    metadata:
      labels:
        app: nodejs-webapp
    spec:
      containers:
        - name: nodejs-container
          image: your-dockerhub-username/nodejs-webapp:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nodejs-webapp
